
version: "3"
services:
  python:
    image: dionysus11/synology-torrent-autodownload:0.0.3
    ports:
    - "20220:20220"
    security_opt:
      - seccomp=./chrome.json
    volumes:
    - ./image/CronManager.py:/app/CronManager.py
    - ./image/TorrentDownloader.py:/app/TorrentDownloader.py
    - ./schedule.json:/app/download/schedule.json