
version: "3"
services:
  python:
    image: dionysus11/synology-torrent-autodownload:0.0.2
    ports:
    - "20220:20220"
    security_opt:
      - seccomp=./chrome.json
    volumes:
    - ./:/app/download