
version: "3"
services:
  python:
    image: dionysus11/synology-torrent-autodownload:0.1.1-amd64
#    platform: linux/amd64
    ports:
    - "20220:20220"
#    shm_size: "2g"
#    security_opt:
#      - seccomp=./chrome.json
    volumes:
    - ./image/CronManager.py:/app/CronManager.py
    - ./image/TorrentDownloader.py:/app/TorrentDownloader.py
    - ./schedule.json:/app/download/schedule.json
    - ./image/run_test.py:/app/run_test.py
    entrypoint:
      - pytest
      - run_test.py