FROM python:3.9
# actually python image is debian based
ENV DEBIAN_FRONTEND noninteractive
RUN pip install --upgrade pip
# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /app
#COPY requirements.txt ./
COPY ./ ./
RUN chmod +x CronManager.py
RUN ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
RUN pip install -r requirements.txt --no-cache-dir
RUN apt update -y && apt install vim libgl1-mesa-glx sudo chromium chromium-driver -y
RUN useradd -ms /bin/bash newuser
RUN chown -R newuser:newuser /app
USER newuser
RUN mkdir -p /app/download
CMD [ "python", "CronManager.py"]